from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional

class DBConfigInterface(ABC):
    """Access DB connection details."""
    @abstractmethod
    def get_chroma_host(self) -> str: ...
    @abstractmethod
    def get_chroma_port(self) -> int: ...
    @abstractmethod
    def get_collection_name(self, source: str) -> str: ...
    @abstractmethod
    def get_s3_container_endpoint(self) -> str: ...
    @abstractmethod
    def get_s3_local_endpoint(self) -> Optional[str]: ...
    @abstractmethod
    def get_s3_bucket_name(self) -> str: ...
class LoggingConfigInterface(ABC):
    """Access logging settings."""
    @abstractmethod
    def get_log_level(self) -> str: ...
    @abstractmethod
    def get_log_format(self) -> Optional[str]: ...
    @abstractmethod
    def get_log_datefmt(self) -> Optional[str]: ...
class LLMConfigInterface(ABC):
    """Access LLM service and model names."""
    @abstractmethod
    def get_ollama_endpoint(self) -> str: ...
    @abstractmethod
    def get_llm_model_name(self) -> str: ...
    @abstractmethod
    def get_llm_options(self) -> Dict[str, Any]: ...
    @abstractmethod
    def get_embedding_model_name(self) -> str: ...
    @abstractmethod
    def get_reranker_model_name(self) -> str: ...
class PipelineConfigInterface(ABC):
    """Access parameters for data pipelines."""
    @abstractmethod
    def get_signal_sampling_rate(self) -> int: ...
    @abstractmethod
    def get_signal_freq_range(self) -> List[float]: ...
    @abstractmethod
    def get_signal_notch_freq(self) -> Optional[int]: ...
    @abstractmethod
    def get_document_chunk_params(self) -> Dict[str, int]: ...
    @abstractmethod
    def get_transcript_chunk_params(self) -> Dict[str, int]: ...
    @abstractmethod
    def get_youtube_videos(self) -> List[str]: ...
    @abstractmethod
    def get_acns_document_name(self) -> str: ...
class RAGCoreConfigInterface(ABC):
    """Access core RAG hyperparameters."""
    @abstractmethod
    def get_n_search(self) -> int: ...
    @abstractmethod
    def get_n_final_signal(self) -> int: ...
    @abstractmethod
    def get_n_final_document(self) -> int: ...
    @abstractmethod
    def get_n_final_transcript(self) -> int: ...
    @abstractmethod
    def get_rrf_k(self) -> int: ...
class MiscConfigInterface(ABC):
    """Access general settings."""
    @abstractmethod
    def get_kaggle_competition_name(self) -> Optional[str]: ...
class BenchmarkConfigInterface(ABC):
    """Access parameters for the evaluation benchmark."""

    @abstractmethod
    def get_api_url(self) -> str: ...
    @abstractmethod
    def get_api_name(self) -> str: ...
    @abstractmethod
    def get_api_timeout(self) -> int: ...
    @abstractmethod
    def get_api_payload(self) -> Dict[str, Any]: ...
    @abstractmethod
    def get_test_file(self) -> str: ...
    @abstractmethod
    def get_results_dir(self) -> str: ...
    @abstractmethod
    def get_provider_config(self, provider_name: str) -> Dict[str, Any]: ...